### ISSUE TITLE
PURLs for LOGGERHEAD

### ISSUE THREAD

**Issue by jamesaoverton** [OBOFoundry/purl.obolibrary.org#46]
I'm getting a 500. I think the BBOP redirect is circular. @cmungall

**Comment by cmungall** [comment]
This ontology has no products:

```
---
layout: ontology_detail
id: loggerhead
title: Loggerhead nesting
contact:
  email: Peter Midford
  label: peteremidford@yahoo.com
homepage: http://www.mesquiteproject.org/ontology/Loggerhead/index.html
is_obsolete: true
---

A demonstration of ontology construction as a general technique for coding ethograms and other descriptions of behavior into machine understandable forms. An ontology for Loggerhead sea turtle (<i>Caretta caretta</i>) nesting behavior, based on the published ethogram of Hailman and Elowson.
```
