### ISSUE TITLE
Need rule for non-numeric GNO IRIs

### ISSUE THREAD

**Issue by nataled** [OBOFoundry/purl.obolibrary.org#614]
I recall that PRO needed special treatment for its non-numeric identifiers (those based on UniProtKB accessions). The situation is the same for GNO. Unlike PRO, the destination page for GNO would still be Ontobee. Would something like the following be needed in obo.yml?

```
# Term redirects for GNO
# Match digits or GlyTouCan ID
- regex: ^/obo/GNO_(\d+|G[0-9]{5}[A-Z]{2})$
  replacement: http://www.ontobee.org/ontology/GNO?iri=http://purl.obolibrary.org/obo/GNO_$1
  status: see other
  tests:
  - from: /GNO_00000001
    to: http://www.ontobee.org/ontology/GNO?iri=http://purl.obolibrary.org/obo/GNO_00000001
  - from: /GNO_G00982CE
    to: http://www.ontobee.org/ontology/GNO?iri=http://purl.obolibrary.org/obo/GNO_G00982CE
```

@edwardsnj Can you confirm the regex? Hopefully I didn't mess it up, but I believe GNO identifiers are either a simple 8 digits (I didn't specify 8 because the same wasn't done for PRO) or are based on GlyTouCan identifiers, which appear to all be G followed by 5 digits followed by 2 of any letter.

@jamesaoverton assigned to you because you helped me with the same issue for PRO. Feel free to reassign, or I'm willing to make the change in obo.yml myself if the above is correct.
