### ISSUE TITLE
Add d2p and g2p files here?

### ISSUE THREAD

**Issue by drseb** [OBOFoundry/purl.obolibrary.org#681]
@matentzn or anybody else: do you think I can add the links to d2p and g2p files (something similar to go-gene-association files) at this place:
https://github.com/OBOFoundry/purl.obolibrary.org/blob/ec0618b76408d058e26d8704661d2cb1af6dff48/config/hp.yml#L12

thanks for any help

**Comment by matentzn** [comment]
This is a policy question; I would say yes, but better ask @cmungall. Note that when something is added to the yaml file it can never be removed.

**Comment by matentzn** [comment]
So the question is: can we add non ontology artefacts logically belonging to our ontology as primary products in the yaml file like:

```
products:
- hp.owl: https://raw.githubusercontent.com/obophenotype/human-phenotype-ontology/master/hp.owl
- hp.obo: https://raw.githubusercontent.com/obophenotype/human-phenotype-ontology/master/hp.obo
- hp.json: https://raw.githubusercontent.com/obophenotype/human-phenotype-ontology/master/hp.json
- hpao-d2p.tsv: uri
```

**Comment by matentzn** [comment]
If you wanted to host the files on github, you of course dont need to do anything.. you could place them in a folder `annotations` and then the purl http://purl.obolibrary.org/obo/hp/annotations/hpao-d2p.tsv would work even without further configuration (because of the generic fallthrough).

**Comment by jamesaoverton** [comment]
Please use a subdirectory or something, not `products`.

**Comment by matentzn** [comment]
I agree, I guess the question was posed because of a need to redirect somewhere outside the fall through. But even that should be possible right? 

You could do:

```
entries:
- prefix: /hpoa-d2p.tsv
  replacement: http://compbio.charite.de/hudson/job/hpo.ontology.uberpheno/lastStableBuild/artifact/data/out/hpoa.tsv

- prefix: /releases/
  replacement: https://raw.githubusercontent.com/obophenotype/human-phenotype-ontology/v
```
