### ISSUE TITLE
Migrate obolibrary.org domain from Google Domains to Route 53

### ISSUE THREAD

**Issue by kltm** [OBOFoundry/purl.obolibrary.org#771]
As we centralize more on AWS and start looking to switch to a new server set (https://github.com/OBOFoundry/purl.obolibrary.org/issues/754), it would be very good to convert over to Rout 53.

We would need to:
- [x] decide what account to migrate to (GO, new, or other) <br /> from @cmungall , we'll use GO
- [x] create IAM users for all parties that should have access <br /> @jamesaoverton and @abessiari should now have access
- [x] setup pre-transfer route 53 record for obolibrary.org <br /> created hosted domain doe the only thing apparently active/used: purl.obolibrary.org
- [x] check that records match <br /> @jamesaoverton confirms that records match
- [x] choose a person with time and knowledge to perform the process <br /> @kltm volunteering
- [x] have that person get access to the google domains account, with help from James <br /> @kltm  browser now seems to be recognized and can login (but for how long?)
- [x] see if a step-by-step transfer guide can be found for google domains to route 53 (otherwise we'll need to wing it a little with the route 53 docs)
- [ ] safely perform the migration, maintaining the current state of the DNS records

After this is done, it would also be pretty quick to do the purl server switchover. We should probably decide whether we want to pursue the switchover first, or get this done first.

Discussed, tagging @jamesaoverton @cmungall @abessiari 

We need to decide the first item there, which is Chris's call.

**Comment by kltm** [comment]
@jamesaoverton For the next item, I'll need a little information from you--question asked on slack.

**Comment by kltm** [comment]
@jamesaoverton Okay, doing a little poking around, while there are several DNS records for obolibrary.org floating around (mostly pointers to absent servers). would I be correct in the statement: `purl.obolibrary.org` is the only record that any uses or needs at this point from the `obolibrary.org` domain?

**Comment by jamesaoverton** [comment]
I see four records in Google Domains. This is a complete and correct list, and they're all in current use.

This is Google's custom YAML format:

```yaml
---
kind: dns#resourceRecordSet
name: 'obolibrary.org.'
rrdatas:
- '131.243.192.69'
ttl: 10800
type: A
---
kind: dns#resourceRecordSet
name: 'editor.obolibrary.org.'
rrdatas:
- '34.232.212.247'
ttl: 3600
type: A
---
kind: dns#resourceRecordSet
name: 'purl.obolibrary.org.'
rrdatas:
- '52.3.123.63'
ttl: 300
type: A
---
kind: dns#resourceRecordSet
name: 'robot.obolibrary.org.'
rrdatas:
- 'ontodev.github.io.'
ttl: 3600
type: CNAME
```

This is the same thing in BIND format:

```
obolibrary.org. 10800 IN A 131.243.192.69
editor.obolibrary.org. 3600 IN A 34.232.212.247
purl.obolibrary.org. 300 IN A 52.3.123.63
robot.obolibrary.org. 3600 IN CNAME ontodev.github.io.
```
